spring:
  redis:
    host: test.redis.daoyitong.com
    port: 6379
    pool:  
      max-active: 8  
      max-idle: 8  
      min-idle: 0  
      max-wait: -1
  datasource:
    data-source-class-name: com.mysql.jdbc.Driver
    username: admin
    password: dyt_mysql_456
    initial-size: 10
    maximum-pool-size: 300
    max-idle: 30
    min-idle: 2
    max-wait: 60000
    max-active: 1000
    connection-test-query: select 1
    validation-interval: 30000
    validation-query: select 1
    time-between-eviction-runs-millis: 3600000
    min-evictable-idle-time-millis: 18000000
    default-read-only: false
    test-on-borrow: true
    test-on-return: true
    test-while-idle: true
    read-only: true
    jdbc-interceptors: org.apache.tomcat.jdbc.pool.interceptor.ConnectionState;org.apache.tomcat.jdbc.pool.interceptor.StatementFinalizer
eureka:
  client:
    healthcheck:
      enable: true
    serviceUrl:
      defaultZone: test.eureka.daoyitong.com:8761/eureka
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
    preferIpAddress: true
logging:
  level:
    root: info
    com:
      ikang:
        mybatis:
          mapper: debug
swagger:
  host: api-test.daoyitong.com/cloud
mybatis:
  mapper-locations: classpath*:config/mybatis/mapper/*.xml
endpoints:
  restart:
    enabled: true
unwork:
  year: 2018
  excludeWeekDay:
  - day: 04-07
    desc: 清明节调换工作日
  - day: 04-28
    desc: 劳动节调换工作日
  holidays:
  - day: 01-01
    desc: 元旦休假
  - day: 02-15|02-16|02-17|02-18|02-19|02-20|02-21
    desc: 春节休假
  - day: 04-05|04-06
    desc: 清明节休假
  - day: 04-29|04-30|05-01
    desc: 劳动节休假
  - day: 06-16|06-17|06-18
    desc: 端午节休假
  - day: 09-22|09-23|09-24
    desc: 中秋节休假
  - day: 10-01|10-02|10-03|10-04|10-05|10-06|10-07
    desc: 国庆节休假
access: 
  together: 
    service: 
      order: http://api.uat.daoyitong.com:88/pavo-access/together/order/list
      patient: http://api.uat.daoyitong.com:88/pavo-access/together/patient/list
      phoneNo: http://api.uat.daoyitong.com:88/pavo-access/together/patient/phoneNo
      finance: http://api.uat.daoyitong.com:88/pavo-access/together/finance/recharge
    img: 
      order: http://static.uat.daoyitong.com:88/accompany_order_img@3x.png

