unwork:
  year: 2018
  excludeWeekDay: 
    - dto: { day: [04-07], desc: 清明节调换工作日 }
    - dto: { day: [04-28], desc: 劳动节调换工作日 }
  holidays:
    - dto: { day: [01-01], desc: 元旦休假 }
    - dto: { day: [02-15,02-16,02-17,02-18,02-19,02-20,02-21], desc: 春节休假 }
    - dto: { day: [04-05,04-06], desc: 清明节休假 }
    - dto: { day: [04-29,04-30,05-01], desc: 劳动节休假 }
    - dto: { day: [06-16,06-17,06-18], desc: 端午节休假 }
    - dto: { day: [09-22,09-23,09-24], desc: 中秋节休假 }
    - dto: { day: [10-01,10-02,10-03,10-04,10-05,10-06,10-07], desc: 国庆节休假 }
