
spring:
  application:
    name: general
eureka:
  client:
    healthcheck:
      enable: true
    serviceUrl:
      defaultZone: http://user:8888@192.168.220.96:8761/eureka
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
    preferIpAddress: true
redis:
  host: 192.168.220.96
  port: 6379
logging:
  level:
    root: info
server:
  port: 7000
endpoints:
  restart:
    enabled: true
zuul:
  url: http://192.168.220.96:5555 #zuul地址，用以restTemplate调用
service:
  demo: demo #serviceName
invoke:
  demo:
    FuGaoOutpatientInfo: ${zuul.url}/${service.demo}/v1/FuGaoOutpatientInfo #erTong加载科室
    FuGaoOutDoctorInfo: ${zuul.url}/${service.demo}/v1/FuGaoOutDoctorInfo?MZDM={MZDM} #erTong加载某科室的所有医生
    FuGaoGetPreResources: ${zuul.url}/${service.demo}/v1/FuGaoGetPreResources?KSDM={KSDM}&YSGH={YSGH}&KSRQ={KSRQ}&JSRQ={JSRQ}

    getSrvGroup: ${zuul.url}/${service.demo}/v1/getSrvGroup?identifyID=FCD8EF688A02518AC7C27A22292CDC64&districtID=1&bookingTypeID={bookingTypeID}
    DepartmentList: ${zuul.url}/${service.demo}/v1/departmentList

    GetDeptInfo: ${zuul.url}/${service.demo}/v1/getDeptInfo #加载科室
    GetItemInfo: ${zuul.url}/${service.demo}/v1/getItemInfo #加载所有医生
    GetPlanInfo: ${zuul.url}/${service.demo}/v1/getPlanItem?fromDate={fromDate}&toDate={toDate} #获取出诊项目
