
spring:
  application:
    name: general
eureka:
  client:
    healthcheck:
      enable: true
    serviceUrl:
      defaultZone: http://user:8888@192.168.220.96:8761/eureka
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
    preferIpAddress: true
redis:
  host: 192.168.220.96
  port: 6379
logging:
  level:
    root: info
server:
  port: 7000
endpoints:
  restart:
    enabled: true
zuul:
  url: http://192.168.220.96:5555 #zuul地址，用以restTemplate调用
service:
  demo: demo #serviceName
hosp:
  renjixi:
    GetDeptInfo: ${zuul.url}/${service.demo}/v1/getDeptInfo #加载科室
invoke:
  demo:
    FuGaoOutpatientInfo: ${zuul.url}/${service.demo}/v1/FuGaoOutpatientInfo #具体的调用url
