spring:
  datasource:
    url: jdbc:mysql://192.168.99.207/dyt_together?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    data-source-class-name: com.mysql.jdbc.Driver
    username: pavo
    password: pavo
    initial-size: 10
    maximum-pool-size: 300
    max-idle: 30
    min-idle: 2
    max-wait: 60000
    max-active: 1000
    connection-test-query: select 1
    validation-interval: 30000
    validation-query: select 1
    time-between-eviction-runs-millis: 3600000
    min-evictable-idle-time-millis: 18000000
    default-read-only: false
    test-on-borrow: true
    test-on-return: true
    test-while-idle: true
    read-only: true
    jdbc-interceptors: org.apache.tomcat.jdbc.pool.interceptor.ConnectionState;org.apache.tomcat.jdbc.pool.interceptor.StatementFinalizer
    schema: classpath*:database/ddl/*-peerlocal.sql
    data: classpath*:database/dml/*-peerlocal.sql
  application:
    name: together-dev
  cache:
    type: redis
eureka:
  client:
    healthcheck:
      enable: true
    serviceUrl:
      defaultZone: http://user:8888@192.168.220.96:8761/eureka
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
    preferIpAddress: true
redis:
  host: 127.0.0.1
  port: 6379
logging:
  level:
    root: info
    com:
      ikang:
        mybatis:
          mapper: debug
server:
  port: 9200
mybatis:
  mapper-locations: classpath*:config/mybatis/mapper/*.xml
  type-aliases-package: com.ikang.together.entity
together:
  getUserOrder: http://192.168.220.96:5555/together/user/order
access: 
  together: 
    service: 
      order: http://api.daoyitong.com/pavo-access/together/order/list
      patient: http://api.daoyitong.com/pavo-access/together/patient/list
      phoneNo: http://api.daoyitong.com/pavo-access/together/patient/phoneNo
      finance: http://api.daoyitong.com/pavo-access/together/finance/recharge
staticResource:
  url: http://static.uat.daoyitong.com:88/
  uploadPath: /home/jason.wu/img-upload
  uploadUrl: http://192.168.220.210:9100/file/uploadFileSingle
  findByIdUrl: http://192.168.220.210:9100/file/urlAllpath/byIds
