spring:
  datasource:
    url: jdbc:mysql://192.168.99.207/test001?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    data-source-class-name: com.mysql.jdbc.Driver
    username: pavo
    password: pavo
    initial-size: 10
    maximum-pool-size: 300
    max-idle: 30
    min-idle: 2
    max-wait: 60000
    max-active: 1000
    connection-test-query: select 1
    validation-interval: 30000
    validation-query: select 1
    time-between-eviction-runs-millis: 3600000
    min-evictable-idle-time-millis: 18000000
    default-read-only: false
    test-on-borrow: true
    test-on-return: true
    test-while-idle: true
    read-only: true
    jdbc-interceptors: org.apache.tomcat.jdbc.pool.interceptor.ConnectionState;org.apache.tomcat.jdbc.pool.interceptor.StatementFinalizer
  application:
    name: action
eureka:
  client:
    healthcheck:
      enable: true
    serviceUrl:
      defaultZone: http://user:8888@192.168.220.96:8761/eureka
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
    preferIpAddress: true
redis:
  host: 192.168.220.96
  port: 6379
logging:
  level:
    root: info
server:
  port: 9000
mybatis:
  mapper-locations: classpath*:config/mybatis/mapper/*.xml
  type-aliases-package: com.ikang.action.entity
excel:
  export:
    dateTime: 日期
    actions:
      - actionId: 0
        cellhead: 体检预约模块
      - actionId: 1
        cellhead: 齿科预约模块
      - actionId: 2
        cellhead: 分诊大厅模块
      - actionId: 3
        cellhead: 预约挂号模块
      - actionId: 4
        cellhead: 健康保险模块
      - actionId: 5
        cellhead: 就医陪诊模块
      - actionId: 6
        cellhead: 基因检测模块
      - actionId: 7
        cellhead: 运动计步模块
      - actionId: 8
        cellhead: 健康商城模块
      - actionId: 9
        cellhead: 电话医生模块
      - actionId: 10
        cellhead: EXTRA服务模块
