server:
  port: 5555
  tomcat:
    accesslog:
      enabled: true
  error:
    whitelabel:
      enabled: false
spring: 
  application: 
    name: zuul-gateway
eureka: 
  client: 
    serviceUrl:
      defaultZone: http://user:8888@192.168.0.12:8761/eureka,http://user:8888@192.168.0.13:8761/eureka,http://user:8888@192.168.0.14:8761/eureka
    healthcheck:
      enable: true
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${server.port}
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    api-a: #服务动态路由映射
      path: /demo/**
      serviceId: demo
    api-b:
      path: /api/v1/zuul/action/**
      serviceId: action
    api-c:
      path: /sms/**
      serviceId: sms
    api-d:
      path: /together/**
      serviceId: together
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:  
  ReadTimeout: 60000  
  ConnectTimeout: 60000
