server:
  port: 5555
  tomcat:
    accesslog:
      enabled: true
  error:
    whitelabel:
      enabled: false
spring:
  application: 
    name: zuul-gateway
  http:
    multipart:
      maxFileSize: 100Mb
      maxRequestSize: 1000Mb
eureka: 
  client: 
    serviceUrl:
      defaultZone: http://user:8888@192.168.220.96:8761/eureka
    healthcheck:
      enable: true
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${server.port}
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    extra: #服务动态路由映射
      path: /extra/**
      url: http://192.168.220.253:50303/
    shop: 
      path: /shop/**
      url: http://192.168.220.253:50304/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:  
  ReadTimeout: 60000  
  ConnectTimeout: 60000
