server:
  port: 5555
  tomcat:
    accesslog:
      enabled: true
  error:
    whitelabel:
      enabled: false
spring: 
  application: 
    name: zuul-gateway
  http:
    multipart:
      maxFileSize: 100Mb
      maxRequestSize: 1000Mb
eureka: 
  client: 
    serviceUrl:
      defaultZone: http://user:8888@192.168.220.210:8761/eureka
    healthcheck:
      enable: true
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${server.port}
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    api-a: #服务动态路由映射
      path: /demo/**
      serviceId: demo
    api-b:
      path: /api/v1/action/**
      serviceId: action
    api-c:
      path: /sms/**
      serviceId: sms
    api-d:
      path: /together/**
      serviceId: together
    api-e:
      path: /card/**
      serviceId: card
    api-f:
      path: /goods/**
      serviceId: goods
    api-g:
      path: /filesys/**
      serviceId: filesys
    api-h:
      path: /balance/**
      serviceId: balance
    api-i:
      path: /physicalexam/**
      serviceId: physicalexam
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:  
  ReadTimeout: 60000  
  ConnectTimeout: 60000
swagger:
  title: spring-boot-starter-swagger
  description: Starter for swagger 2.x
  version: 1.2.0.RELEASE
  license: Apache License, Version 2.0
  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfServiceUrl: https://github.com/dyc87112/spring-boot-starter-swagger
  contact:
    name: MAX.LIU
    url: http://www.baidu.com
    email: coaf@qq.com
  base-package: com.ikang
  base-path: /**
  exclude-path: /error, /ops/**
swagger.docket.filesys.title=标题
swagger.docket.filesys.description=描述
swagger.docket.filesys.version=版本
swagger.docket.filesys.license=许可证
swagger.docket.filesys.licenseUrl=许可证URL
swagger.docket.filesys.termsOfServiceUrl= http://192.168.220.210:9100/swagger-ui.html#/
swagger.docket.filesys.contact.name=维护人
swagger.docket.filesys.contact.url=维护人URL
swagger.docket.filesys.contact.email=维护人email
swagger.docket.filesys.base-package=swagger扫描的基础包，默认：全扫描
swagger.docket.filesys.base-path=需要处理的基础URL规则，默认：/**
swagger.docket.filesys.exclude-path=需要排除的URL规则，默认：空
