spring:
  datasource:
    url: jdbc:mysql://uat.mysql.daoyitong.com/pavo_balance?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
  application:
    name: balance
server:
  port: 9500
mybatis:
  type-aliases-package: com.ikang.balance.entity
access: 
  together: 
    service: 
      finance: http://api-test.daoyitong.com/pavo-access/together/finance/recharge
order:
  update:
    paydown: http://test.shoporder.daoyitong.com:50304/shop/order/update #直接调用shop
  search:
    byid: http://api-test.daoyitong.com/api/v1/shop/order/list #从rest转发到shop
  refund:
    refundservice: http://api-test.daoyitong.com/api/v1/refund/refundService #从rest转发到shop
rest:
  msg:
    listmsg: http://api-test.daoyitong.com/api/v1/card/sendMsg
extraOrder:
  search:
    getOrderInfo: http://test.medical.daoyitong.com:50303/serviceOrder/getOrderInfo/
  update: 
    serviceOrder: http://test.medical.daoyitong.com:50303/serviceOrder/update
