spring:
  datasource:
    url: jdbc:mysql://dev.mysql.daoyitong.com/pavo_rpc?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    data-source-class-name: com.mysql.jdbc.Driver
    username: admin
    password: dyt_mysql_456
    initial-size: 10
    maximum-pool-size: 300
    max-idle: 30
    min-idle: 2
    max-wait: 60000
    max-active: 1000
    connection-test-query: select 1
    validation-interval: 30000
    validation-query: select 1
    time-between-eviction-runs-millis: 3600000
    min-evictable-idle-time-millis: 18000000
    default-read-only: false
    test-on-borrow: true
    test-on-return: true
    test-while-idle: true
    read-only: true
    jdbc-interceptors: org.apache.tomcat.jdbc.pool.interceptor.ConnectionState;org.apache.tomcat.jdbc.pool.interceptor.StatementFinalizer
    schema: classpath*:database/ddl/*-dev.sql
    data: classpath*:database/dml/*-dev.sql
  application:
    name: rpc
eureka:
  client:
    healthcheck:
      enable: true
    serviceUrl:
      defaultZone: http://user:8888@192.168.220.210:8761/eureka
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
    preferIpAddress: true
redis:
    host: dev.redis.daoyitong.com
    port: 6379
    pool:  
      max-active: 8  
      max-idle: 8  
      min-idle: 0  
      max-wait: -1
logging:
  level:
    root: info
    com:
      ikang:
        mybatis:
          mapper: debug
server:
  port: 8081
mybatis:
  mapper-locations: classpath*:config/mybatis/mapper/*.xml
  type-aliases-package: com.ikang.goods.entity
testaaa:
  testbbb:
    testccc: ttttt
endpoints:
  restart:
    enabled: true
jingdongprop:
  oauth2: https://bizapi.jd.com/oauth2/
  product: https://bizapi.jd.com/api/product/
  price: https://bizapi.jd.com/api/price/
  order: https://bizapi.jd.com/api/order/
  area: https://bizapi.jd.com/api/area/
jingdong:
  token:
    accessToken: ${jingdongprop.oauth2}accessToken #获取token
    refreshToken: ${jingdongprop.oauth2}refreshToken #refresh token
  product:
    getPageNum: ${jingdongprop.product}getPageNum #获取商品池
    getSkuByPage: ${jingdongprop.product}getSkuByPage #获取sku编号
    getDetail: ${jingdongprop.product}getDetail #获取商品详情
    skuState: ${jingdongprop.product}skuState #获取商品上下架状态
    skuImage: ${jingdongprop.product}skuImage #获取商品图片
    getCommentSummarys: ${jingdongprop.product}getCommentSummarys #获取好评度
    checkAreaLimit: ${jingdongprop.product}checkAreaLimit #商品区域购买限制
    getIsCod: ${jingdongprop.product}getIsCod #商品区域知否支持货到付款
    getSkuGift: ${jingdongprop.product}getSkuGift #查询赠品信息
    getFreight: ${jingdongprop.order}getFreight #运费查询
    search: https://bizapi.jd.com/api/search/search #商品搜索
    check: ${jingdongprop.product}check #商品可售验证
    getYanbaoSku: ${jingdongprop.product}getYanbaoSku #查询商品延保
    getCategory: ${jingdongprop.product}getCategory #查询分类信息
    getCategorys: ${jingdongprop.product}getCategorys #查询分类列表信息
    getSimilarSku: ${jingdongprop.product}getSimilarSku #同类商品查询
  price:
    getSellPrice: ${jingdongprop.price}getSellPrice #批量查询商品售卖价
  area:
    getProvince: ${jingdongprop.area}getProvince #获取一级地址
    getCity: ${jingdongprop.area}getCity #获取二级地址
    getCounty: ${jingdongprop.area}getCounty #获取三级地址
    getTown: ${jingdongprop.area}getTown #获取四级地址
    checkArea: ${jingdongprop.area}checkArea #验证四级地址是否正确
    getJDAddressFromAddress: ${jingdongprop.area}getJDAddressFromAddress #根据地址查询京东地址编码.v1
