spring:
  redis:
    host: dyt-redis.ikang.com
    port: 6379
    pool:  
      max-active: 8  
      max-idle: 8  
      min-idle: 0  
      max-wait: -1
  datasource:
    url: jdbc:mysql://db.dyt.ikang.com:3306/pavo_card?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    data-source-class-name: com.mysql.jdbc.Driver
    username: daoyitong
    password: pavo_daoyitong!@$
    initial-size: 10
    maximum-pool-size: 300
    max-idle: 30
    min-idle: 2
    max-wait: 60000
    max-active: 1000
    connection-test-query: select 1
    validation-interval: 30000
    validation-query: select 1
    time-between-eviction-runs-millis: 3600000
    min-evictable-idle-time-millis: 18000000
    default-read-only: false
    test-on-borrow: true
    test-on-return: true
    test-while-idle: true
    read-only: true
    jdbc-interceptors: org.apache.tomcat.jdbc.pool.interceptor.ConnectionState;org.apache.tomcat.jdbc.pool.interceptor.StatementFinalizer
    schema: classpath*:database/ddl/*-product.sql
    data: classpath*:database/dml/*-product.sql
  application:
    name: card
eureka:
  client:
    healthcheck:
      enable: true
    serviceUrl:
      defaultZone: http://user:8888@192.168.0.12:8761/eureka,http://user:8888@192.168.0.13:8761/eureka,http://user:8888@192.168.0.14:8761/eureka
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
    preferIpAddress: true
logging:
  level:
    root: info
    com:
      ikang:
        mybatis:
          mapper: debug
server:
  port: 9400
mybatis:
  mapper-locations: classpath*:config/mybatis/mapper/*.xml
  type-aliases-package: com.ikang.card.entity
cloud:
  balance:
    recharge: http://api.daoyitong.com/cloud/balance/recharge
  goods:
    getServiceByGoodsId: http://api.daoyitong.com/cloud/goods/getServiceByGoodsId
    addgoods: http://api.daoyitong.com/cloud/goods/pc/admin/card/add
  physicalexam:
    findPackageByExamId: http://api.daoyitong.com/cloud/physicalexam/findPackageByExamId
    addExamResource: http://api.daoyitong.com/cloud/physicalexam/addExamResource  #添加爱康体检卡密
medicalservice:
  memberRights:
    add: http://192.168.0.40:50303/memberRights/add
rest:
  msg:
    listmsg: http://api.daoyitong.com/api/v1/card/sendMsg
admin:
  account:
    registeraccounts: http://api.daoyitong.com/admin/account/registerAccounts
