spring:
  datasource:
    url: jdbc:mysql://test.mysql.daoyitong.com:3306/pavo_card?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
  application:
    name: card
server:
  port: 9400
mybatis:
  type-aliases-package: com.ikang.card.entity
cloud:
  balance:
    recharge: http://api-test.daoyitong.com/cloud/balance/recharge
  goods:
    getServiceByGoodsId: http://api-test.daoyitong.com/cloud/goods/getServiceByGoodsId
    addgoods: http://api-test.daoyitong.com/cloud/goods/pc/admin/card/add
  physicalexam:
    findPackageByExamId: http://api-test.daoyitong.com/cloud/physicalexam/findPackageByExamId
    addExamResource: http://api-test.daoyitong.com/cloud/physicalexam/addExamResource  #添加爱康体检卡密
medicalservice:
  memberRights:
    add: http://api-test.daoyitong.com/admin/serviceMedical/memberRights/add
rest:
  msg:
    listmsg: http://api-test.daoyitong.com/api/v1/card/sendMsg
admin:
  account:
    registeraccounts: http://api-test.daoyitong.com/admin/account/registerAccounts
