spring:
  redis:
    host: dev.redis.daoyitong.com
    port: 6379
    pool:  
      max-active: 8  
      max-idle: 8  
      min-idle: 0  
      max-wait: -1
  datasource:
    url: jdbc:mysql://dev.mysql.daoyitong.com/pavo_physicalexam?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    data-source-class-name: com.mysql.jdbc.Driver
    username: admin
    password: dyt_mysql_456
    initial-size: 10
    maximum-pool-size: 300
    max-idle: 30
    min-idle: 2
    max-wait: 60000
    max-active: 1000
    connection-test-query: select 1
    validation-interval: 30000
    validation-query: select 1
    time-between-eviction-runs-millis: 3600000
    min-evictable-idle-time-millis: 18000000
    default-read-only: false
    test-on-borrow: true
    test-on-return: true
    test-while-idle: true
    read-only: true
    jdbc-interceptors: org.apache.tomcat.jdbc.pool.interceptor.ConnectionState;org.apache.tomcat.jdbc.pool.interceptor.StatementFinalizer
    schema: classpath*:database/ddl/*-dev.sql
    data: classpath*:database/dml/*-dev.sql
  application:
    name: physicalexam
eureka:
  client:
    healthcheck:
      enable: true
    serviceUrl:
      defaultZone: http://user:8888@192.168.220.210:8761/eureka
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
    preferIpAddress: true
logging:
  level:
    root: info
    com:
      ikang:
        mybatis:
          mapper: debug
server:
  port: 9900
mybatis:
  mapper-locations: classpath*:config/mybatis/mapper/*.xml
  type-aliases-package: com.ikang.physicalexam.entity
physicalexam:
  source:
    statusdesc:
      - statusCode: 0
        statusText: 未绑定
      - statusCode: 1
        statusText: 已绑定，未使用
      - statusCode: 2
        statusText: 已使用，待预约
      - statusCode: 3
        statusText: 已预约，未到检
      - statusCode: 4
        statusText: 已预约，但取消
      - statusCode: 5
        statusText: 已到检，未生成报告
      - statusCode: 6
        statusText: 已生成报告
      - statusCode: -1
        statusText: 过期未使用
cloud:
  ikang:
    onlyCode: fNE7NVk$4*sz5@5 #UAT环境商家唯一码
    findHospInfoByCode: http://uatservices.health.ikang.com/ikang-service/rs/cooperation/findHospInfoByCode #根据套餐CODE查询体检中心信息
    findExamRecordInfo: http://uatservices.health.ikang.com/ikang-service/rs/cooperation/findExamRecordInfo #预约单查询
    findReportInfo: http://uatservices.health.ikang.com/ikang-service/rs/cooperation/findReportInfo #报告查询接口
    findSupportDayByHospIdUrl: https://uatservices.health.ikang.com/ikang-service/rs/cooperation/findServiceOrderDay #根据hospid获取体检机构排期
    confirmReservationUrl: https://uatservices.health.ikang.com/ikang-service/rs/cooperation/saveOrderInfo #预约单保存
    cancelOrder: https://uatservices.health.ikang.com/ikang-service/rs/cooperation/cancelOrder #取消订单
    updateOrderDate: https://uatservices.health.ikang.com/ikang-service/rs/cooperation/updateOrderDate #预约单改期
    findCheckDataBack: https://uatservices.health.ikang.com/ikang-service/rs/cooperation/findCheckDataBack #预约到检查询
    registrationUser: https://uatservices.health.ikang.com/ikang-service/rs/cooperation/registrationUser #体检人注册
    getResultInfos: https://uatservices.health.ikang.com/ikang-service/rs/cooperation/getResultInfos #体检报告结构化数据查询接口
    getResultInfoPlus: https://uatservices.health.ikang.com/ikang-service/rs/cooperation/getResultInfoPlus #体检报告结构化数据查询接口(含诊断)
  filesys:
    uploadFileSingle: http://api-dev.daoyitong.com/cloud/filesys/file/uploadFileSingle #单文件上传
    urlAllPath: http://api-dev.daoyitong.com/cloud/filesys/file/urlAllpath/byIds #多文件全路径查看(Map格式)
